import droneImageUrl1 from "./../assets/images/design.jpg";
import droneImageUrl2 from "./../assets/images/2.png";
import MainBgImg from "./../assets/images/aircraftsBG.jpg";
import droneImageUrl3 from "./../assets/images/fixed-wing1.png"
import droneImageUrl4 from "./../assets/images/fixed-wing2.jpg"

 const AircraftData = [

    {
        url: MainBgImg,
        title: "Sky Weaver",
        id: 1,
        flightTime: "45 Minutes",
        TransmissionRange: "15 KM",
        LiveFeed: "4k/60fps",
        Positioning: "Accurate Positioning",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },
    {
        url: droneImageUrl2,
        title: "Nimbus Scout",
        id: 2,
        flightTime: "1 Hour",
        TransmissionRange: "25 KM",
        LiveFeed: "2k/60fps",
        Positioning: "Precise Location",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },

    {
        url: droneImageUrl3,
        title: "Aero Phantom",
        id: 3,
        flightTime: "45 Hours",
        TransmissionRange: "95 KM",
        LiveFeed: "8k/60fps",
        Positioning: "Ground Control",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },

    {
        url: MainBgImg,
        title: "Vector Glide",
        id: 4,
        flightTime: "15 Minutes",
        TransmissionRange: "10 KM",
        LiveFeed: "1k/60fps",
        Positioning: "Environmental Awareness",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },

    {
        url:droneImageUrl1,
        title: "Echo Raptor",
        id: 5,
        flightTime: "125 Minutes",
        TransmissionRange: "30 KM",
        LiveFeed: "4k/30fps",
        Positioning: "Underwater Detection",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },

    {
        url: droneImageUrl4,
        title: "Zenith Eye",
        id: 6,
        flightTime: "45 Hours",
        TransmissionRange: "120 KM",
        LiveFeed: "16k/120fps",
        Positioning: "Heat Signature Detection",

        keyHighlights1: "Quick Deployment",
        keyHighlights2: "Tool-Less Assembly",
        keyHighlights3: "Swappable Battery",
        keyHighlights4: "Hot Swappable Payloads",

        TechnicalDetails1: "Advanced Hybrid Composite Material",
        TechnicalDetails2: "650mm wheel base",
        TechnicalDetails3: "Empty Weight - 1KG",
        TechnicalDetails4: "Wind Resistance Index - 30Knots",
        TechnicalDetails5: "Communication Links - 2.4Ghz,900Mhz(encrypted)",
        TechnicalDetails6: "Range Control&Telemetry - 10kms LOS",
        TechnicalDetails7: "Cruise Speed - 8ms",
        TechnicalDetails8: "Dash Speed - 10m/s",
        TechnicalDetails9: "Service Ceiling - 4000m AMSL",
        TechnicalDetails10: "Operational Altitude - 500mAGL",
        TechnicalDetails11: "Propulsion - Brushless Electric",

        Feature1: "HD Resolution Cam -4k, 10x,Optical Zoom",
        Feature2: "Active Obstacle Avoidance - Upto 10m",
        Feature3: "Gimbal Stabilization - 3 axis stabilized",
        Feature4: "Aural Signature - 40dB@300m AGL",
        Feature5: "Portability - Back Packable",
        Feature6: "Operational Temperature - -10 to 50c",
        Feature7: "Operating Environment - Multi Terrain",

        UseCases1: "For rapid surveillance, MQ650lv drone is the ideal solution",
        UseCases2: "The MQ650lv drone is ideally suited for rapid mapping use cases, delivering precise and efficient geospatial data",
        UseCases3: "The MQ650lv drone's capabilities make it a vital asset for tactical-level reconnaissance, enabling commanders to make informed decisions with timely and accurate intelligence",
        UseCases4: "For tactical law enforcement, the MQ650lv drone offers invaluable aerial perspective,during high-risk operations,  aiding in suspect apprehension and ensuring officer safety.",
        UseCases5: "The MQ650lv drone is exceptionally well-suited for the use case of tactical traffic monitoring",
    },

];

export default AircraftData;